name: Build API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and Tag the Docker image
        run: |
          docker build ./api --file ./api/Dockerfile --tag ghcr.io/zerix-defi/zerix-api:$TIMESTAMP
          docker tag ghcr.io/zerix-defi/zerix-api:$TIMESTAMP ghcr.io/zerix-defi/zerix-api:latest

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/zerix-defi/zerix-api:$TIMESTAMP
          docker push ghcr.io/zerix-defi/zerix-api:latest

      - name: Restart Deployment on Kubernetes
        run: |
          /usr/local/bin/kubectl rollout restart deployment zerix-api --namespace=zerix-ai-test